MyDiplomProject/MyDiplomProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('profils/', include('profils.urls', namespace='profils')),

]

MyDiplomProject/profils/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path, reverse_lazy
from .views import Render_Main, UserLoginView, UserLogoutView, Render_glavn, Registration, MyAccount, Projects, \
    CreateProject, Show_Projects

app_name = 'profils'

urlpatterns = [
    path('main/', Render_Main, name='main'),
    path('logun_users/', UserLoginView.as_view(), name='logun_users'),
    path('logout_users/', UserLogoutView.as_view(), name='logout_users'),
    path('glavn_str/', Render_glavn, name='rend_glavn'),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="profils/password_reset_form.html",
             email_template_name="profils/password_reset_email.html",
             success_url=reverse_lazy("profils:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="profils/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="profils/password_reset_confirm.html",
                                          success_url=reverse_lazy("profils:password_reset_complete")),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetDoneView.as_view(template_name="profils/password_reset_complete.html"),
         name='password_reset_complete'),

    path('registration/', Registration.as_view(), name='Registration'),
    path('projects/<int:id>/', Show_Projects, name='detail_project'),
    path('my_account/', MyAccount, name='MyAccount'),
    path('projects/', Projects, name='projects'),
    path('create_projects/', CreateProject.as_view(), name='CreateProjects'),

]

MyDiplomProject/profils/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    """Расширяем базовую модель User"""
    mail = models.EmailField(unique=True, blank=True, null=True)
    number = models.CharField(max_length=12,blank=True, null=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Создает и сохраняет пользователя с введенным им email и паролем.
        """
        if not email:
            raise ValueError('email должен быть указан')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class Projcets(models.Model):
    """Модель проектов"""
    name_project = models.CharField(max_length=255, default='Тестовый', unique=False, null=False, blank=False)
    is_wireless_tech = models.BooleanField(default=True)
    is_cloud_tech = models.BooleanField(default=True)
    is_virtual_tech = models.BooleanField(default=True)
    protection_class = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.protection_class} {self.is_virtual_tech}"

    def get_absolute_url(self):
        return reverse('profils:detail_project', kwargs={'id': self.pk})
class R_person(models.Model):
    """Ответственные за проект"""
    name = models.CharField(max_length=255)
    appointment = models.CharField(max_length=255)

MyDiplomProject/profils/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import path
from django.views import View
from django.views.generic import ListView

from .models import User, Projcets
from . import views
from django.contrib.auth import views as auth_views, login, authenticate, logout


def Render_Main(request):
    return render(request, 'profils/main.html')


@login_required(login_url='profils:logun_users')
def Render_glavn(request):
    return render(request, 'profils/glavn_str.html')


class UserLoginView(View):

    def post(self, request):
        user = authenticate(username=request.POST['login'], password=request.POST['password'])
        if user:
            login(request, user)
            return redirect('profils:rend_glavn')
        return render(request, 'profils/logun_users.html')

    def get(self, request):
        return render(request, 'profils/logun_users.html')


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('profils:main')


class Registration(View):
    def post(self, request):
        User.objects.create_user(username=request.POST['login'], password=request.POST['password'],
                                 email=request.POST['mail'])
        return render(request, 'profils/logun_users.html')

    def get(self, request):
        return render(request, 'profils/registration.html')


@login_required(login_url='profils:logun_users')
def MyAccount(request):
    return render(request, 'profils/my_account.html')






class CreateProject(View):

    def post(self, request):
        if request.POST['is_wireless_tech'] == 'True':
            is_wireless = True
        else:
            is_wireless = False
        if request.POST['is_cloud_tech'] == 'True':
            is_cloud = True
        else:
            is_cloud = False
        if request.POST['is_virtual_tech'] == 'True':
            is_virtual = True
        else:
            is_virtual = False

        print('1')
        Projcets.objects.create(name_project=request.POST['name_project'],
                                is_wireless_tech=is_wireless,
                                is_cloud_tech=is_cloud,
                                is_virtual_tech=is_virtual,
                                protection_class=request.POST['protection_class'],
                                user_id=request.user.id)
        return render(request, 'profils/my_projects.html')

    def get(self, request):
        print(request)
        print(1)
        return render(request, 'profils/create_project.html')

@login_required(login_url='profils:logun_users')
def Projects(request):
    users_project = Projcets.objects.filter(user_id=request.user.id)
    data = {
        'projects': users_project
    }
    return render(request, 'profils/my_projects.html', context=data)

def Show_Projects(request,id):
    users_project = Projcets.objects.filter(id=id)
    return HttpResponse(f"Отображение статьи с id = {users_project[0].id}")

MyDiplomProject/profils/templates/profils/create_project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action = "{% url 'profils:CreateProjects' %}" method="post">
        {% csrf_token %}
        <p>name_project</p>
        <input type="text" name="name_project">
        <p>is_wireless_tech</p>
        <input type="text" name="is_wireless_tech">
        <p>is_cloud_tech</p>
        <input type="text" name="is_cloud_tech" />
        <p>is_virtual_tech</p>
        <input type="text" name="is_virtual_tech" />
        <p>protection_class</p>
        <input type="text" name="protection_class" />
        <p><input type="submit" value="Create"></p>
</form>
</body>
</html>

MyDiplomProject/profils/templates/profils/detail_project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Тут мы видим информацию о проекте</p>


</body>
</html>

MyDiplomProject/profils/templates/profils/glavn_str.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Сюда попадает пользователь после авторизации</p>
<p>Привет {{ request.user }}</p>
<a href="{% url 'profils:logout_users' %}">Выйти</a>
<a href="{% url 'profils:MyAccount' %}">Профиль</a>
<a href="{% url 'profils:projects' %}">Мои проекты</a>
</body>
</html>

MyDiplomProject/profils/templates/profils/logun_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Тут форма для логина</p>
<form action = "{% url 'profils:logun_users' %}" method="post">
        {% csrf_token %}
        <p>Логин</p>
        <input type="text" name="login">
        <p>Пароль</p>
        <input type="password" name="password" />
        <p><input type="submit" value="Log-in"></p>
</form>
<a href="{% url 'profils:Registration' %}">Регистрация</a>
<a href="{% url 'profils:password_reset' %}">Забыли пароль?</a>
</body>
</html>

MyDiplomProject/profils/templates/profils/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Превью</title>
</head>
<body>
<p>Эту страницу видит пользователь</p>
{{ request.user }}
<p>Превью</p>
<div>
    <p>О нас</p>
    <a href="{% url 'profils:logun_users' %}">Войти</a>
</div>
</body>
</html>

MyDiplomProject/profils/templates/profils/my_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
</head>
<body>
<p>{{ request.user }} это страница вашего профиля, тут вы можете что то</p>
<p>Смена пароля</p>
<form>
    {% csrf_token %}
        <p>Смена имени</p>
        <input type="text" name="login">
        <p><input type="submit" value="Log-in"></p>
</form>
</body>
</html>

MyDiplomProject/profils/templates/profils/my_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Тут пользователь видит свои проекты</p>
<a href="">Создать проект</a>
</body>
</html>

MyDiplomProject/profils/templates/profils/my_projects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Проекты пользователя</p>
<a href="{% url 'profils:CreateProjects' %}">Создать проект</a>
{% for project in projects.all %}
    <p>{{project.name_project}}</p>
    <a href="{{ project.get_absolute_url }}">Подробнее</a>
{% endfor %}
</body>
</html>

MyDiplomProject/profils/templates/profils/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Пароль изменен</h1>
<a href="{% url 'users:logun_users' %}">Страница входа</a>
</body>
</html>

MyDiplomProject/profils/templates/profils/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Новый пароль</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  <input type="password" name="password" />
  <p><input type="submit" value="Сохранить"></p>
</form>
</body>
</html>

MyDiplomProject/profils/templates/profils/password_reset_done.html
{% load i18n %}


{% block content %}
<h1>Сброс пароля</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

MyDiplomProject/profils/templates/profils/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'profils:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

MyDiplomProject/profils/templates/profils/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
  Страница для смена пароля по email
  <input type="email" name="email">
  <button type="submit">Сбросить по E-mail</button>
</form>

</body>
</html>

MyDiplomProject/profils/templates/profils/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Форма регистрации</p>
<form action = "{% url 'profils:Registration' %}" method="post">
        {% csrf_token %}
        <p>Логин</p>
        <input type="text" name="login">
        <p>Mail</p>
        <input type="email" name="mail">
        <p>Пароль</p>
        <input type="password" name="password" />
        <p><input type="submit" value="Log-in"></p>
</form>
</body>
</html>